name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}

    - run: |
        docker build -t docker.pkg.github.com/delta10/kubectl/kubectl:latest .
        docker push docker.pkg.github.com/delta10/kubectl/kubectl:latest
